---
# maintains versions and can overwrite all.yml
gnoland:
  chain_id: test-13
  genesis_url: https://github.com/gnolang/gno/releases/download/chain/test13/genesis.json
  validator:
    version: chain/test13
    go:
      version: 1.25.9
    exporter_endpoint: "http://{{ monitor_server_dns }}:4323"
  snapshot_url: https://snapshots.nodesync.top/Testnet/Gno/gnoland_snap.tar.lz4
