---
# maintains versions and can overwrite all.yml
gnoland:
  chain_id: test6
  validator:
    version: chain/test6
    go:
      version: 1.23.1
    exporter_endpoint: "http://{{ monitor_server_dns }}:4323"
  snapshot_url: https://snapshot.shazoes.xyz/testnets/snapshot-gnoland.tar.lz4
