---
# maintains testnet inventory grouped by project names
all:
  vars:
    env: testnet
  children:
    gnoland:
      hosts:
        validator.gnoland.testnet.encapsulate.xyz:
          type: validator
