---
- name: Ensure tmp directory exists
  ansible.builtin.file:
    path: "{{ tmp_dir }}"
    state: directory
    mode: "1777"

- name: Clone the repository to /tmp
  ansible.builtin.git:
    repo: "{{ vars[project][type].source_url }}"
    dest: "{{ tmp_dir }}/{{ project }}"
    version: "{{ vars[project][type].version }}"
    force: true

- name: Build Gnoland binary
  ansible.builtin.shell: |
    go build -ldflags "-w -s" -o build/gnoland ./gno.land/cmd/gnoland
  args:
    chdir: "{{ tmp_dir }}/{{ project }}"
    executable: /bin/bash
  environment:
    PATH: "{{ go.root }}/bin:{{ ansible_env.PATH }}"
    GOROOT: "{{ go.root }}"
    GOPATH: "{{ go.path }}"
    GO111MODULE: "{{ go.module111 }}"

- name: Copy the built binary to the target directory
  ansible.builtin.copy:
    src: "{{ tmp_dir }}/{{ project }}/build/{{ node_service_default_binary_name }}"
    dest: "{{ node_bin_dir }}/{{ service_identifier }}"
    mode: "0755"
    owner: root
    group: root
    remote_src: true
    force: true
  notify:
    - Restart service

- name: Copy gnovm to the target directory
  ansible.builtin.copy:
    src: "{{ tmp_dir }}/{{ project }}/gnovm"
    dest: "{{ node_home_dir }}"
    mode: "0755"
    owner: root
    group: root
    remote_src: true
    force: true
  notify:
    - Restart service

- name: Clean up the temporary repository directory
  ansible.builtin.file:
    path: "{{ tmp_dir }}/{{ project }}"
    state: absent
