---
- name: Poll blockchain height until it reaches upgrade height
  ansible.builtin.uri:
    url: http://localhost:{{ rpc_port }}/{{ node_status_endpoint }}
    method: GET
    return_content: true
  register: blockchain_height
  ignore_errors: true # Do not fail the task if the request fails

- name: Display waiting message
  ansible.builtin.debug:
    msg: "Waiting for blockchain height to reach upgrade height. Current: {{ blockchain_height.json.result.sync_info.latest_block_height }}, Remaining blocks: {{
      upgrade_height | int - blockchain_height.json.result.sync_info.latest_block_height | default(0) | int }}"

- name: Pause for 30 seconds
  ansible.builtin.pause:
    seconds: 30

- name: Include poll height task
  ansible.builtin.include_tasks: coordinated_update.yml
  when: (blockchain_height.json.result.sync_info.latest_block_height | default('0') | int) != (upgrade_height | int)
