---
- name: Stop service
  ansible.builtin.systemd:
    name: "{{ service_identifier }}"
    state: stopped

- name: Delete data folder
  ansible.builtin.file:
    path: "{{ sync_data_dir }}"
    state: absent

- name: Delete wal folder
  ansible.builtin.file:
    path: "{{ sync_home_dir }}/wal"
    state: absent

- name: Download and Extract snapshot
  ansible.builtin.shell: |
    set -o pipefail
    curl -o - -L {{ snapshot_url | default(vars[project].snapshot_url) }} | lz4 -c -d - | tar -x -C {{ sync_home_dir }}
  async: 10000
  poll: 10
  args:
    executable: /bin/bash
    creates: "{{ sync_data_dir }}"

- name: Set ownership for data directory
  ansible.builtin.file:
    path: "{{ sync_data_dir }}"
    owner: "{{ service_identifier }}"
    group: "{{ service_identifier }}"
    recurse: true

- name: Handle wal logic
  block:
    - name: Set ownership for wal directory
      ansible.builtin.file:
        path: "{{ sync_home_dir }}/wal"
        owner: "{{ service_identifier }}"
        group: "{{ service_identifier }}"
        recurse: true
  rescue:
    - name: Handle missing wal directory
      ansible.builtin.debug:
        msg: wal direcotry does't present in home directory

- name: Restart service
  ansible.builtin.systemd:
    name: "{{ service_identifier }}"
    state: restarted
